### ISSUE TITLE
How to run the test suite?

### ISSUE THREAD

**Issue by MaxG87** [guilatrova/tryceratops#16]
I wanted to implement some fuzzing tests using [Hypothesis](hypothesis.readthedocs.io/). Before, I wanted to run the test suite unchanged. Unfortunately I couldn't manage to do so. The project neither has a `setup.py` nor a meaningful [Poetry](https://python-poetry.org/) setup nor a [tox](tox.readthedocs.io/) setup.

I think one of these should be there to allow externals to reproduce the test suite. If they all are undesired, a brief section in the README.md would be very helpful.

**Comment by guilatrova** [comment]
Thanks for the push, yes, I should make it more clear.

For now, what you need is:

```
# I suggest creating your own virtualenv here
# Install dependencies
pip install -r dev-requirements.txt

# Run package installer
flit install --sym

# Run tests
pytest
```

Let me know if it works for you!

And that should be it. I need to see if adding poetry makes sense since we already have flit (poetry does more than flit, but flit is simpler to publish IMHO).

**Comment by guilatrova** [comment]
I created a new [contributing doc](https://github.com/guilatrova/tryceratops/blob/main/docs/CONTRIBUTING.md) and created a new issue to track the new CI/CD flow (with Poetry) that would benefit the whole project: https://github.com/guilatrova/tryceratops/issues/19
