### ISSUE TITLE
Better naming: tryceratops and triceratops

### ISSUE THREAD

**Issue by kseistrup** [guilatrova/tryceratops#3]
Isn't the naming unfortunate when there is already a Python module called triceratops?

* https://pypi.org/project/triceratops/
* https://pypi.org/project/tryceratops/

**Comment by guilatrova** [comment]
Yes, I guess so 😥

Let's see how this project evolves, we might rename it later on. Do you have any ideas for a possible name?

**Comment by kseistrup** [comment]
> Do you have any ideas for a possible name?

Hm…, if you tell us the background for the name “tryceratops”, perhaps we can find another saurus that fits in well. Is it a reference to `try`−`except`?

**Comment by kseistrup** [comment]
#### List of dinosaur genera

⌘ https://en.wikipedia.org/wiki/List_of_dinosaur_genera

**Comment by guilatrova** [comment]
> Hm…, if you tell us the background for the name “tryceratops”, perhaps we can find another saurus that fits in well. Is it a reference to try−except?

I never thought too much about it. Indeed, it's just a "funny" game of words between `try` - except and `triceratops`.

**Comment by kseistrup** [comment]
Right. Well, I'll bounce it around in my head and will let you know if I can think of something.

**Comment by RojerGS** [comment]
`exceptosaurus` and `try-rex` come to mind :P

**Comment by guilatrova** [comment]
hahahaha I loved the "try-rex" 😂

**Comment by guilatrova** [comment]
I'll close it for now. I realized that I don't mind having another project with a similar name. 

If we do really good work, and if the community enjoys what we are building here, then they will never forget the project name 😉 🦖

**Comment by kseistrup** [comment]
You're the boss.
