### ISSUE TITLE
False negative for TC003 long message not detected

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [guilatrova/tryceratops#31]
Hello again :) 

The following code is not raising a `TC003` but I think it should:
```python
import numpy as np


def check_a_b(a: np.ndarray, b: np.ndarray) -> None:
    if len(a) != len(b):
        raise ValueError(
            "cezczeczeczecezczeczecnezklcnzelkczkenclkzecnzeklck"
            f"({len(a)})zedenzcklzelkcnzelcknzeklcnzelkncklzeckl"
            f"({len(b)})dzekckezncknzecklnzeklczkelcklzencknzeck"
        )

```

**Comment by guilatrova** [comment]
Thanks for reporting! I'll take a look and fix this scenario as soon as I have time 🙏

**Comment by RojerGS** [comment]
I was coming here to raise this issue as well.
I managed to realise that `TC003` isn't raised with f-strings.

I also found out that it doesn't appear to issue a `TC003` when it's just one long “word”.

So, the following is flagged with `TC003`:

```py
raise ValueError("01234567890123456789 12345678901234567890123456789")
```

But none of these two are:

```py
raise ValueError("01234567890123456789012345678901234567890123456789")
raise ValueError(f"01234567890123456789 12345678901234567890123456789")
```

**Comment by guilatrova** [comment]
Resolved by https://github.com/guilatrova/tryceratops/pull/75
