### ISSUE TITLE
isinstance(x, Callable) => callable(x)

### ISSUE THREAD

**Issue by sbrugman** [guilatrova/tryceratops#36]
@guilatrova Would you be open to adding a Violation for the following? Not directly related to exceptions other than through [32](https://github.com/guilatrova/tryceratops/issues/32)

```
from typing import Callable

if isinstance(x, Callable):
    pass
```

which should be:
```
if callable(x):
    pass
```

**Comment by guilatrova** [comment]
I'm afraid that if we go through this path, Tryceratops will lose its focus.

Let's stick to try/except and exception scenarios.
