### ISSUE TITLE
Some codes conflicts with `flake8-type-checking` plugin

### ISSUE THREAD

**Issue by diegovalenzuelaiturra** [guilatrova/tryceratops#41]
Hi, thanks for this nice tool!

I just wanted to mention that there are some codes that conflicts with other nice tool: https://pypi.org/project/flake8-type-checking

**Comment by guilatrova** [comment]
Ahh, that's unexpected... We might need to modify our code to `TRY` instead...

Do you have experience using both Tryceratops and `flake8-type-checking`? Does it conflict in a way it's unusable?
