### ISSUE TITLE
Unpin dependencies (or adopt a bot to help upgrade it like Dependabot)

### ISSUE THREAD

**Issue by paw-lu** [guilatrova/tryceratops#47]
Hi! Enjoying the project!

One issue I have come across again is that this project's dependecy pinning causes conflicts with other libraries

It happened once before to Click, and recently again have had trouble with Rich.

- https://github.com/guilatrova/tryceratops/pull/39
- https://github.com/guilatrova/tryceratops/pull/46

Rich itself updates major versions pretty often, so this is likely to happen again in the future.

Two solutions:

1. Unpin the dependencies, [this is becoming more popular](https://iscinumpy.dev/post/bound-version-constraints/). It just involves switching from pining to the major version to just enforcing a minmum version.

    ```diff
    - rich = "^10.14.0"
    + rich = ">=10.14.0"
    ```

2. Use an automation tool like Dependabot to [keep your depenencies up to date, and update often](https://hynek.me/articles/semver-will-not-save-you/).

Happy to help with either of these if you are interested.

Again, thanks for the tool!

_Edit: Wrong article was linked in first point (it supported the second point)_

**Comment by guilatrova** [comment]
Thank you @paw-lu for making such great suggestions and for contributing to the project.

I'll read the article you share since I'm interested, and then share thoughts.

**Comment by guilatrova** [comment]
I got convinced with this article: https://iscinumpy.dev/post/bound-version-constraints/#python-is-not-javascript

I read specific sections, it's very clear to me the problem and I do agree we should solve it. I'll prepare a PR with suggestions and assign it to your for review @paw-lu

**Comment by GlenNicholls** [comment]
> I got convinced with this article: https://iscinumpy.dev/post/bound-version-constraints/#python-is-not-javascript
> 
> I read specific sections, it's very clear to me the problem and I do agree we should solve it. I'll prepare a PR with suggestions and assign it to your for review @paw-lu

Thanks for posting that! I ran into a conflict between rich and tryceratops this morning trying it out and was surprised since my app uses rich, but I wanted to see what kind of feedback tryceratops had about my code.
