### ISSUE TITLE
Generic name when running tryceratops as a module

### ISSUE THREAD

**Issue by RojerGS** [guilatrova/tryceratops#7]
I installed `tryceratops` and `tryceratops.exe` got installed into a folder that is not on my PATH variable.

What I usually do, to run things like `black`, is `python -m black`, and the same thing works for `tryceratops`, naturally.

However, some of the command-line options give generic info back because `__name__` is now `"__main__"`:

```bash
 > python -m tryceratops --version
__main__.py, version 0.2.3
```

and

```bash
 > python -m tryceratops --help
Usage: __main__.py [OPTIONS] [DIR]...
# omitted
```

Notice both appearances of `__main__.py` where I expected `tryceratops` or `tryceratops.py`. In my opinion the `__main__.py` doesn't look good, in a stylistic sense.

**Comment by guilatrova** [comment]
Interesting... I couldn't simulate. What's your OS?

**Comment by RojerGS** [comment]
Windows 10, 64 bit, Python 3.9, `tryceratops` installed for the user, not globally.

**Comment by RojerGS** [comment]
Update: seems like other tools also have this quirk, e.g. `black` shows the same thing.

**Comment by guilatrova** [comment]
Interesting, I'll take a look

**Comment by guilatrova** [comment]
It seems easy to fix. Saving for later: https://github.com/pallets/click/issues/1399

**Comment by guilatrova** [comment]
Done, next release it will be fixed
